name: Deploy Firebase Functions
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Tools
        run: npm install -g firebase-tools
      - name: Install Deps
        run: |
          cd functions
          npm install
      - name: Deploy
        run: npx firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
